name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
      - "3001:3001"
    volumes:
      - /root/hyperliquid-node-data-docker:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - /root/hyperliquid-node-data-docker:/home/hluser/hl/data

volumes:
  hl-data:
    driver: local
